title: Where why who what?
author: Ayman Ali
email: ayman.ali1230@gmail.com
description: Infrequently updated but if you're here may as well ...
twitter_username: namyaila
github_username: namyaila

# Build settings
markdown:  kramdown
theme:  jekyll-theme-minimal